### ISSUE TITLE
utility struct for flags

### ISSUE THREAD

**Issue by tomaskrizek** [NLnetLabs/domain#108]
I'd find it useful if there was a single struct containing the flags from the message header. It'd also be useful if it had a text representation, e.g. "QR AA" and if the struct could be constructed from this string representation as well.

I'd use the same string representation as the dnspython library: https://github.com/rthalley/dnspython/blob/master/dns/flags.py

For now, I'd stick with standard flags only (ignoring EDNS flags), which can be easily constructed from header.

Would this feature make sense to you? If so, I could contribute the code.

**Comment by partim** [comment]
Do you have a reason for not just using the `Header` struct as it is right now? We could add a function to it that creates a value from a string with those flags?

**Comment by tomaskrizek** [comment]
I'm trying to compare flags of different messages and it's useful for me to a have struct that contains only the relevant bits, because then it's easier to compare or hash them. Whether that's a general enough issue to warrant an implementation in this library - I'm not sure.

**Comment by partim** [comment]
If you want to do things with just the flags, it certainly makes sense to have a type for them. So I wouldn’t mind adding it.
