### ISSUE TITLE
Is there a public mailing list or similar channel?

### ISSUE THREAD

**Issue by pemensik** [NLnetLabs/domain#133]
Hello,

I am total newbie in Rust attempting to use domain library. But I have found a lot blockers. Is there a good electronic channel, where I could ask for help with my little project? I guess I would have multiple questions, but I don't think I should use issues here. They are not issues in library itself. They relate just to my inability to use the library in my own application. I find fiddling with domain names and creating raw query with asynchronous lookup hard.

Where can I ask more experimenced people about this library?

**Comment by partim** [comment]
There isn’t anything yet. But I have enabled Discussions on the repository. We can give that a try and see if that works.
