### ISSUE TITLE
Is there way to request DNSSEC Ok enabled answer from stub resolver?

### ISSUE THREAD

**Issue by pemensik** [NLnetLabs/domain#134]
I think stub resolver does not provide any way to modify message of question. It does not allow any customization of outgoing messages. resolv/stub/mod.rs contains create_message. That sets recursion disabled always, even when there is recursion flag in options. I have not found documented way to obtain nameservers parsed from current StubResolver. Only options. Is that intentional?

I wanted to detect, whether the server strips out EDNS or DO flag in OPT section. OPT section is accessible in answer, but I haven't found any trace to put it also into question. Am I wrong?

**Comment by partim** [comment]
The resolver wasn’t really intended to do more complex “DNS-internal” operations but to supply what a resolver in libc would usually do. For more complex things, I would at this point suggest to set up your own transport and message handling. There is a plan to move the transport implementations into a separate module but that hasn’t happened yet.

**Comment by partim** [comment]
There’s now an example on how to do a simple request/response sequence in `examples/client.rs`.

Moving the networking to a separate module will follow later.
