### ISSUE TITLE
SRV record lookup for automatic LDAP domain detection

### ISSUE THREAD

**Issue by 1Dragoon** [NLnetLabs/domain#136]
I'm trying to figure out how to do an SRV record lookup. Basically I want to automate detection of a domain controller. I can't figure out the syntax involved here though as it returns an error that my label syntax is incorrect:

```rust
    let answer = StubResolver::new().lookup_srv(
        RelativeDname::from_octets(b"_ldap._tcp").unwrap(),
        Dname::<Vec<u8>>::from_str("example.com").unwrap(),
        389).await.unwrap();
```

What is the correct way to provide the service parameter?

Also, is there a way to populate the resolver's search suffix list other than manually filling it in? I'm guessing something involving DHCP is needed but I don't know which options to look for, or if there are any crates out there that can pick it up from all major platforms.

Thanks!

**Comment by 1Dragoon** [comment]
Looking at the code, I was able to get passed the label part by doing this:

```rust
RelativeDname::from_octets(b"\x0A_ldap._tcp").unwrap()
```

Though I can't help but wonder if there's another struct I'm supposed to use to create the relativedname that auto derives the length byte?

Anyways at this point it's saying that it's failing:

`
code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host."
`

Not sure which server it's trying to connect to though. I'm able to request srv records using nslookup, so I'm not sure why this would fail.

**Comment by partim** [comment]
The prefix is actually two labels, so the correct value here would be `b"\x05_ldap\x04tcp"`. That said, the easier way would be to use the `FromStr` impl the same way as you did for the base name, i.e., `RelativeDname::<Vec<u8>>::from_str("_ldap._tcp").unwrap()`.

The connection reset error is indeed strange. Configuration for the stub resolver is taken from your local `/etc/resolv.conf`. Is there something odd in there? If not, could you do a quick Wireshark trace to see who it is trying to talk to?

**Comment by 1Dragoon** [comment]
I'm testing this from a windows box, guessing it would pull from the registry. Not really able to use wireshark on this computer unfortunately. I tried an alternative way of doing this that I think is working sufficiently though, so thanks anyways!

**Comment by partim** [comment]
Ah! Unfortunately, when I wrote this code I didn’t have access to a Windows machine. If you happen to be able to point me to documentation on where this information is stored in the registry, I’d love to add a mechanism to configure a stub resolver correctly.
