### ISSUE TITLE
Question: Why do the lookups filter records by owner?

### ISSUE THREAD

**Issue by glts** [NLnetLabs/domain#163]
Looking at the lookups implementation, I see that the result iterators all take care to only return records where the owner matches the canonical name of the answer (?). For example:

https://github.com/NLnetLabs/domain/blob/88206100b264178d4d1eca853ff5deb9dc0609b7/src/resolv/lookup/host.rs#L191

I am currently using `StubResolver` to perform queries without filtering like this, and it seems to be working well. Surely I’m missing some basic thing about DNS. Could you explain why this filtering is necessary? Thank you.

**Comment by partim** [comment]
This is just a precaution against irrelevant records appearing in the message. It shouldn’t happen, but given that we are talking to a remote service, it’s perhaps better to check.
