### ISSUE TITLE
no_std support?

### ISSUE THREAD

**Issue by overheat** [NLnetLabs/domain#179]
I found some comments about `no_std` in the code. But no clear clue.
Anyone know?

**Comment by partim** [comment]
The crate supports `no_std` if the `std` feature is not selected. As it is selected by default, `default-features = false` is required in the dependency definition.

Note that not everything is available without `std`. In particular, the stub resolver currently requires it.

**Comment by partim** [comment]
I’m closing the issue – if you have additional questions, please don’t hesitate to reopen!
