### ISSUE TITLE
mDNS RDATA name compression records

### ISSUE THREAD

**Issue by pusateri** [NLnetLabs/domain#19]
According to Section 18.14 of RFC 6762, name compression can happen in the RDATA of the following record types:

`NS, CNAME, PTR, DNAME, SOA, MX, AFSDB, RT, KX, RP, PX, SRV, NSEC`

**Comment by partim** [comment]
For the moment, only SRV and NSEC are relevant. SRV should already work, NSEC will be fixed.

Note that for the moment at least, we’ll always produce uncompressed record data for both SRV and NSEC. Should this become a problem, compression support needs to be extended.
