### ISSUE TITLE
 function dname_from_addr

### ISSUE THREAD

**Issue by williamdes** [NLnetLabs/domain#218]
Source: https://github.com/NLnetLabs/domain/blob/v0.8.0/src/resolv/lookup/addr.rs#L101

Could this function be public in your crate ?
It's so neat I copied it into my project and linked the source

**Comment by williamdes** [comment]
Nervermind, I found that https://docs.rs/rustdns/0.4.0/rustdns/util/fn.reverse.html has the same function exposed
Maybe you can depend on it

**Comment by partim** [comment]
It’s still a good suggestion and we will provide this in some form …

**Comment by williamdes** [comment]
Okay, thanks for re opening
