### ISSUE TITLE
crash on Option::unwrap()

### ISSUE THREAD

**Issue by ermine** [NLnetLabs/domain#22]
Using domain 0.4 on machos, it always fails.
To reproduce it is  enough to use an example from domain-resolve/examples/downloader.rs.

    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/dtest`
thread 'tokio-runtime-worker-0' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:312
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:49
   9: domain_resolv::stub::resolver::giving_up_error
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/macros.rs:11
  10: domain_resolv::stub::resolver::ResolverInner::from_conf::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-resolv-0.4.0/src/stub/resolver.rs:216
  11: domain_resolv::stub::resolver::Query::next_server
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-resolv-0.4.0/src/stub/resolver.rs:274
  12: domain_resolv::stub::resolver::Query::next_server
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-resolv-0.4.0/src/stub/resolver.rs:331
  13: <domain_resolv::lookup::host::MaybeDone<A>>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-resolv-0.4.0/src/lookup/host.rs:173
  14: <domain_resolv::lookup::host::LookupHost<R> as futures::future::Future>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-resolv-0.4.0/src/lookup/host.rs:130
  15: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/chain.rs:26
  16: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/and_then.rs:32
  17: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/chain.rs:26
  18: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/and_then.rs:32
  19: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/chain.rs:26
  20: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/and_then.rs:32
  21: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/chain.rs:26
  22: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/and_then.rs:32
  23: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/chain.rs:26
  24: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/and_then.rs:32
  25: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/chain.rs:26
  26: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/then.rs:32
  27: <futures::task_impl::NotifyHandle as core::clone::Clone>::clone
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/mod.rs:113
  28: std::sys_common::mutex::Mutex::raw_lock
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:329
  29: std::sys_common::mutex::Mutex::raw_lock
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:399
  30: futures::task_impl::std::CURRENT_THREAD_NOTIFY::__init
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/std/mod.rs:78
  31: std::sys_common::mutex::Mutex::raw_lock
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:399
  32: std::sys_common::mutex::Mutex::raw_lock
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:291
  33: std::sys_common::mutex::Mutex::raw_lock
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:329
  34: tokio_threadpool::task::Task::run::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/task/mod.rs:145
  35: core::ops::function::FnOnce::call_once
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/ops/function.rs:231
  36: core::ptr::swap_nonoverlapping_bytes
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panic.rs:309
  37: crossbeam_utils::backoff::Backoff::snooze
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panicking.rs:297
  38: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  39: crossbeam_utils::backoff::Backoff::snooze
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panicking.rs:276
  40: crossbeam_utils::backoff::Backoff::snooze
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panic.rs:388
  41: tokio_threadpool::task::Task::run
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/task/mod.rs:130
  42: tokio_threadpool::worker::Worker::run_task2
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:567
  43: tokio_threadpool::worker::Worker::run_task
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:459
  44: tokio_threadpool::worker::Worker::try_run_owned_task
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:390
  45: tokio_threadpool::worker::Worker::try_run_task
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:297
  46: tokio_threadpool::worker::Worker::with_current::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:241
  47: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/builder.rs:349
  48: futures::task_impl::std::CURRENT_THREAD_NOTIFY::__init
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-trace-core-0.1.0/src/dispatcher.rs:54
  49: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/builder.rs:348
  50: <tokio_reactor::HandlePriv as core::clone::Clone>::clone
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:94
  51: alloc::raw_vec::alloc_guard
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/local.rs:300
  52: alloc::raw_vec::alloc_guard
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/local.rs:246
  53: <tokio_reactor::HandlePriv as core::clone::Clone>::clone
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:81
  54: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/builder.rs:347
  55: futures::task_impl::core::get_ptr
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:141
  56: alloc::raw_vec::alloc_guard
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/local.rs:300
  57: alloc::raw_vec::alloc_guard
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/local.rs:246
  58: futures::task_impl::core::get_ptr
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:124
  59: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/builder.rs:346
  60: alloc::raw_vec::alloc_guard
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:237
  61: alloc::raw_vec::alloc_guard
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/local.rs:300
  62: alloc::raw_vec::alloc_guard
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/local.rs:246
  63: alloc::raw_vec::alloc_guard
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:217
  64: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/builder.rs:345
  65: tokio_threadpool::callback::Callback::call
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/callback.rs:22
  66: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:127
  67: <tokio_threadpool::task::blocking::State as core::cmp::PartialEq>::eq
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:209
  68: std::sys::unix::mutex::Mutex::destroy
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/local.rs:300
  69: std::sys::unix::mutex::Mutex::destroy
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/local.rs:246
  70: <tokio_threadpool::task::blocking::State as core::cmp::PartialEq>::eq
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:178
  71: tokio_threadpool::worker::Worker::do_run::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:125
  72: std::sys::unix::mutex::Mutex::destroy
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/local.rs:300
  73: std::sys::unix::mutex::Mutex::destroy
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/local.rs:246
  74: tokio_threadpool::worker::Worker::do_run
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:116
  75: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/pool/mod.rs:344
  76: crossbeam_epoch::collector::LocalHandle::is_pinned
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/sys_common/backtrace.rs:135
  77: crossbeam_epoch::default::is_pinned
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/mod.rs:469
  78: core::ptr::swap_nonoverlapping_bytes
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panic.rs:309
  79: crossbeam_utils::backoff::Backoff::snooze
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panicking.rs:297
  80: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  81: crossbeam_utils::backoff::Backoff::snooze
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panicking.rs:276
  82: crossbeam_utils::backoff::Backoff::snooze
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panic.rs:388
  83: crossbeam_epoch::default::is_pinned
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/thread/mod.rs:468
  84: core::alloc::Layout::repeat
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/liballoc/boxed.rs:749
  85: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/liballoc/boxed.rs:759
             at src/libstd/sys_common/thread.rs:14
             at src/libstd/sys/unix/thread.rs:81
  86: _pthread_body
  87: _pthread_start
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:312
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/result.rs:798
  10: tokio::runtime::threadpool::Runtime::block_on
             at /Users/ermine/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.19/src/runtime/threadpool/mod.rs:266
  11: dtest::main
             at src/main.rs:54
  12: std::rt::lang_start::{{closure}}
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  15: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: std::rt::lang_start
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
  17: dtest::main

**Comment by partim** [comment]
Thanks for the report and sorry for the bug! I believe we fixed that in #14. I will make a release during the week so this fix ends up on crates.io.

**Comment by partim** [comment]
I realize now that I never to did a 0.4.1 release before now making some fundamental changes for 0.5.0.

Are you okay with this fix coming to creates.io only in 0.5 with lots of breaking changes in `domain-core` or would you prefer I did a 0.4.1 release of `domain-resolv` before that?

**Comment by partim** [comment]
I’m closing this now. Please let me know if you indeed need that release.
