### ISSUE TITLE
The TXT record concatenates and outputs all character strings

### ISSUE THREAD

**Issue by weilence** [NLnetLabs/domain#259]
If the TXT record is `"aaa" "bbb"`, it should be output as `"aaa" "bbb"` rather than concatenating as `aaabbb`.
Should add `"` display arround in this `for`?
https://github.com/NLnetLabs/domain/blob/bd9fe433d6bbd00611dccf3385b828fcc7447b2e/src/rdata/rfc1035.rs#L1886

the go version:
https://github.com/miekg/dns/blob/21ba49c291a44bd348308dbd01de337dcf0ab7f0/types.go#L556

**Comment by partim** [comment]
Ah yes. This code was based on a misunderstanding of mine assuming that the purpose of a sequence of multiple character strings in a TXT record was so they could be longer than 255 characters.

I suppose it shouldn’t be quoted if it is just a single character string, though?

**Comment by partim** [comment]
Looks like _dig_ quotes it anyway. We’ll do the same, then.

**Comment by weilence** [comment]
> Looks like _dig_ quotes it anyway. We’ll do the same, then.

Additionally, space in the current TXT records will not be escaped. the current implementation will output them as \32.

**Comment by partim** [comment]
I noticed this now as I was writing test cases for a fix.
