### ISSUE TITLE
Consider using features instead of sub-crates

### ISSUE THREAD

**Issue by partim** [NLnetLabs/domain#40]
After actually having used tokio’s new approach of using features atop a single crate rather than minimalist sub-crates, I wonder if maybe we should do the same thing for domain.

I.e., there’d be only one domain crate that contains the various sub-crates such as domain-resolv as an opt-in feature, e.g. `"resolv"`.

The upcoming 0.5 with loads of breaking changes would be a good time to do that. 

Any opinions on this?

**Comment by pusateri** [comment]
I'm ok either way. There's also Cargo Workspaces: 
[https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html]()

**Comment by partim** [comment]
Workspaces is what we’ve been using. But it becomes all a bit unwieldy, really, for maintenance. With features it all seems a bit simpler.

**Comment by partim** [comment]
This has been implemented in 0.5.
