### ISSUE TITLE
Add support for NAPTR record type

### ISSUE THREAD

**Issue by weilence** [NLnetLabs/domain#426]
I noticed that some DNS record types, such as NAPTR, SPF, and CAA, are not yet supported.
I’ve implemented the parsing for NAPTR to prevent it from appearing as a binary string in outputs.
Could you review the code to ensure it follows the project’s coding standards?

**Comment by ximon18** [comment]
Hi @weilence,

Thankyou very much for this contribution!

At first glance it looks very nice. I have some minor observations which I'll add to the PR.

Ximon
