### ISSUE TITLE
Examples are not checked in CI

### ISSUE THREAD

**Issue by tertsdiepraam** [NLnetLabs/domain#437]
We should run `cargo check` on the examples in the CI to prevent breaking them. We cannot run all of them, but we should at least make sure they keep compiling.

**Comment by ximon18** [comment]
Even building the examples would not necessarily work, as they do currently work with `--all-features`. To find issues we would need a way to build (but not run as they don't all terminate or they try to access things on the network) them one at e time using the feature set specified for that example in `Cargo.toml`.

**Comment by ximon18** [comment]
A related issue on the Rust side is: https://github.com/rust-lang/cargo/issues/4663

**Comment by ximon18** [comment]
As a first fix we can manually specify each example to build with the feature set correct at the time of modifying CI, it won't automatically track changes to `Cargo.toml` though so will need updating if the feature set needed to compile the examples changes.

**Comment by tertsdiepraam** [comment]
I could try with some `nushell` scripting? This gets the required features for the `lookup` example:
```
open Cargo.toml | get "example" | find name == "lookup" | get "required-features".0
```
