### ISSUE TITLE
Plan for DoT / DoH in the stub resolver

### ISSUE THREAD

**Issue by vavrusa** [NLnetLabs/domain#5]
Hello 👋 do you have any immediate plans for supporting DoT / DoH in the stub resolver?

**Comment by partim** [comment]
They are definitely the next things on the list for the stub resolver. For reasons of other work, I don’t want to make a promise about the timeframe, though.

That said, naive DoT that reconnects for each and every query should be doable in pretty much no time at all. But I am not sure if that is even worth bothering with.

**Comment by vavrusa** [comment]
Ok, thanks!
