### ISSUE TITLE
Flesh out APIs for synchronous (non-async) use cases?

### ISSUE THREAD

**Issue by glts** [NLnetLabs/domain#66]
This is more a weak suggestion or a question, feel free to close. I’m
using domain-resolv in a library that does not use async Rust, it only
does synchronous DNS resolution. That library is meant for long-running
programs, and will repeatedly invoke `StubResolver::run`.

As far as I understand, `StubResolver::run` is not meant to be used in
this way, as it has a per-call overhead of instantiating an async
runtime etc.

As a consequence, non-async consumers of domain-resolv have to create
and manage an async runtime themselves, and have to depend directly on
async packages like tokio, even though they are not themselves actually
async libraries or applications.

The question for me is whether the state of affairs described above is
as-designed, or whether the ‘story’ for synchronous consumers could be
fleshed out, in the sense that consumers would be able to use
domain-resolv without requiring any knowledge or dependencies on async
Rust. I note that I am not an expert user, that is, my interest is in a
simple and easy-to-use synchronous DNS resolution facility (use case is
SPF protocol).

Thank you.

**Comment by partim** [comment]
First, apologies: I completely missed your question about the runtime-related overhead of `StubResolver::run` in #65. You are, of course, right that creating a new Tokio runtime for each query must be expensive. Although, exactly how expensive might be interesting to benchmark.  

There’s actually another thing that `run` does and that is kind of important: It creates a new `StubResolver` and currently, only during creation `resolv.conf` is read. So right now you should probably indeed recreate a `StubResolver` regularly unless you know you are on a server and the resolver configuration likely won’t change.

So this all really does need a bunch of redesigning. I will investigate what the best way to provide a long-living, regularly used stub resolver is. I want to merge `domain_resolv` into `domain` as soon as rustc allows that – which would be a good time for some breaking changes.

**Comment by partim** [comment]
As a side note: if you want to add (or have added) SPF record parsing to `domain`, I’d be up for that. We could have a generic TXT record type that can parse TXT content.

**Comment by glts** [comment]
Thank you @partim for your answer.

> As a side note: if you want to add (or have added) SPF record parsing to `domain`, I’d be up for that. We could have a generic TXT record type that can parse TXT content.

Well, I do have a working SPF data model with parser [here](https://docs.rs/viaspf/0.0.2/viaspf/model/index.html). The scope seems very different though, so not sure it would fit in domain (and obviously the design is not nearly as sophisticated as domain … work in progress)

**Comment by glts** [comment]
After some restructuring happened in my application the original motivation for this issue disappeared. `StubResolver::run_with_conf` now works well for me. I won’t be following this issue closely for now, so feel free to close.Cheers

**Comment by glts** [comment]
I'm happy with domain today and will now close this request.
