### ISSUE TITLE
Random things discovered when porting to domain=0.5

### ISSUE THREAD

**Issue by vavrusa** [NLnetLabs/domain#68]
Hi, I ended up adding a bunch of helper functions over time as I was updating to the 0.5 domain library, and I thought some of it might be useful in the base library itself. Maybe there's a nicer way of doing this stuff, so I thought I would open this ticket first to see what would make sense / when there's a better way to do things. I'm happy to open PRs for things you thing would be good to add.

1. There are some convenience functions missing for converting names and records from one octets to another, so I created a bunch of helpers:

```
/// Creates a root domain over any octets.
pub fn root_name<O>() -> Result<Dname<O>> where O: FromBuilder;

/// Convert name to canonical format (equivalent to "to_dname()" but also converts to canonical format)
pub fn to_canonical_name<O>(name: impl ToDname) -> Dname<O> where O: FromBuilder;

/// Convert OctetsRef into owned Octets.
pub fn to_octets<O, R>(o: R) -> Result<O> O: FromBuilder;
```

2. Some RecordData types (I think Ds or Dnskey) have "convert()" method which makes this easier, but most don't so they need to be recreated. This is useful when for example recreating trust anchors from static data into a Record backed by any other storage type, or storing records from `Message<&[u8]>` in cache with a  different storage type. I've added this convenience conversion function like this, but it's still a bit tedious. Perhaps some sort of "convert()" method would be useful for all types?

```
/// Convert Record into another Record with different RDATA.
pub fn from_record<N: ToDname, O: FromBuilder, D, DD, F: FnOnce(D) -> Result<DD>>(
    rr: Record<N, D>,
    f: F,
) -> Result<Record<Dname<O>, DD>>;
``` 

3. In most projects I have a need to print or debug messages in some sort of text format. I've implemented an extension trait for various wrapper structures that implement `std::fmt::Display`. Perhaps that would be useful in the domain library as well?

```
/// Extension for `domain::Message` for pretty printing.
pub trait MessageExt<O> {
    /// Formats the message question as a shorthand "<query name> <query_type>".
    fn as_formatted_query(&self) -> FmtQuery<O>;
    /// Formats the message and records using a dig-like text format.
    fn as_formatted_text(&self) -> FmtMessageText<O>;
    /// Formats the message and records using a short text format.
    fn as_formatted_short(&self) -> FmtMessageShort<O>;
}
```

**Comment by vavrusa** [comment]
Another thing that's tricky is `MasterRecordData<O, N> -> MasterRecordData<OO, NN>`. Not sure if there's a better solution for this than Compose into OO::Builder + Parse?

**Comment by partim** [comment]
Thanks for the suggestions! There definitely is a bunch of stuff that needs adding to make the library more useful out of the box.

> There are some convenience functions missing for converting names and records from one octets to another, so I created a bunch of helpers:
> 
> 
> ```
> /// Creates a root domain over any octets.
> pub fn root_name<O>() -> Result<Dname<O>> where O: FromBuilder;
> ```

Isn’t `Dname::root` doing what you want? If the missing `From<&'static [u8]>` trait bound is an issue, we should implement it for the octet types in question.

> ```
> /// Convert name to canonical format (equivalent to "to_dname()" but also converts to canonical format)
> pub fn to_canonical_name<O>(name: impl ToDname) -> Dname<O> where O: FromBuilder;
> ```

Makes sense. I guess it should go into the `ToDname` trait?

> ```
> /// Convert OctetsRef into owned Octets.
> pub fn to_octets<O, R>(o: R) -> Result<O> O: FromBuilder;
> ```

Maybe all of the methods that convert between octets types should be called `convert`? I guess that’s what it does?

> Some RecordData types (I think Ds or Dnskey) have "convert()" method which makes this easier, but most don't so they need to be recreated. This is useful when for example recreating trust anchors from static data into a Record backed by any other storage type, or storing records from `Message<&[u8]>` in cache with a  different storage type. I've added this convenience conversion function like this, but it's still a bit tedious. Perhaps some sort of "convert()" method would be useful for all types?

Yes. I think they are really just missing and can be added. Maybe we should have a checklist for new record types?

> In most projects I have a need to print or debug messages in some sort of text format. I've implemented an extension trait for various wrapper structures that implement `std::fmt::Display`. Perhaps that would be useful in the domain library as well?
> 
> 
> ```
> /// Extension for `domain::Message` for pretty printing.
> pub trait MessageExt<O> {
>     /// Formats the message question as a shorthand "<query name> <query_type>".
>     fn as_formatted_query(&self) -> FmtQuery<O>;
>     /// Formats the message and records using a dig-like text format.
>     fn as_formatted_text(&self) -> FmtMessageText<O>;
>     /// Formats the message and records using a short text format.
>     fn as_formatted_short(&self) -> FmtMessageShort<O>;
> }
> ```

That seems useful, indeed. `std::path::Path` calls its equivalent method `display`, so maybe `display_query`, `display_long`, and `display_short` as names? I think that makes it more obvious what this is for?

> Another thing that's tricky is `MasterRecordData<O, N> -> MasterRecordData<OO, NN>`. Not sure if there's a better solution for this than Compose into OO::Builder + Parse?

We can have a `convert` method here, too, if all types that need conversion have a convert method themselves. Might need some trickery with the macro definition.
