### ISSUE TITLE
Example only supports query for a single domain, not multiple as accepted on the CLI

### ISSUE THREAD

**Issue by whh8b** [NLnetLabs/domain#7]
This is a great code base (does exactly what I want!) but the example for how to use domain_resolv (domain-resolv/examples/lookup.rs) is misleading.

The CLI accepts multiple addresses and gives the impression that it is going to resolve each of those iteratively. Based on the code, this is not what happens. Only the first of the addresses on the CLI is resolved. The remainder are just dropped. 

Is this something that is known? I'd be happy to make changes to the example, if that's something that you would want!

Thanks again for the great tool!
Will

**Comment by partim** [comment]
Thanks for the compliments!

Looks like I misinterpreted what `Stream::into_future` does, so this is a bug, indeed. Should be an easy fix, though.
