### ISSUE TITLE
FYI similar project: Trust DNS

### ISSUE THREAD

**Issue by u24b6** [NLnetLabs/domain#78]
https://github.com/bluejekyll/trust-dns

Contains both libraries and binaries. Implements different transports. Seems quite fleshed out.

Also has done a fair bit of performance optimization: https://bluejekyll.github.io/blog/rust/2017/12/29/making-trust-dns-fast.html

There are also some other Trust DNS related blog posts the author has written that you may want to try out.

**Comment by partim** [comment]
We are quite aware of Trust DNS – it is a great project.

The intention of this crate is slightly different: it aims to provide basic building blocks for specialist, niche DNS applications.
