### ISSUE TITLE
Drop `core::bits` and merge content into `core`.

### ISSUE THREAD

**Issue by partim** [NLnetLabs/domain#8]
Now that there is a separate `domain::core` crate, it feels like the `bits` module is an unnecessary extra indirection and could be dropped, merging all its contents into `domain::core` directly.

This would require some changes in `use` statements all over the code using `domain::core`. As a mitigation, we could keep `bits` for a while and re-export what already is in there now.

**Comment by pusateri** [comment]
I think a flag day would be fine. Just announce when you're going to do it, make the change, and make a new release.

**Comment by partim** [comment]
It’ll probably happen in 0.5.0 together with the changes I am working on to be able to use the crate in `no_std` environments (the [octet-slices](https://github.com/NLnetLabs/domain/tree/octet-slices) branch). While I am trying to do that this as transparently as possible, there’s bound to be some porting involved there, too.

**Comment by partim** [comment]
Never mind the `no_std` thing. It feels to much of a burden for the regular use case which I imagine to be more common. So instead I just went ahead and merged bits in #32.
