### ISSUE TITLE
Update Message Builder

### ISSUE THREAD

**Issue by pusateri** [NLnetLabs/domain#9]
How do you want to handle building Update messages? Should it be part of MessageBuilder? Should there be a separate UpdateBuilder?

**Comment by pusateri** [comment]
Or should I use MessageBuilder as normal and just change the opcode?

**Comment by partim** [comment]
It was indeed the idea that `MessageBuilder` works for all kind of messages.

I only added `QueryBuilder` to make reusing a query easier as it has exactly one question and optionally one OPT record that may need to be changed between targeted servers. Eventually, I would want to fold it back into `MessageBuilder`.

**Comment by pusateri** [comment]
ok, thanks.
