### ISSUE TITLE
docs.rs does not show documentation for resolv module, and maybe others as well

### ISSUE THREAD

**Issue by CameronNemo** [NLnetLabs/domain#97]
Do I need to generate the documentation locally for modules which are disabled by default?

**Comment by partim** [comment]
Looks like we need to provide a hint for docs.rs. I will make a 0.6.1 release soon that will fix that. Until then, you indeed will have to build the documentation locally.

**Comment by partim** [comment]
Done. The documentation on docs.rs looks complete now.

Thanks for reporting!
